#pragma once

#define MIDI_BASIC
#define ENCODER_RESOLUTION 4

// Mouse Configs
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 2

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 1

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 1

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 1

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 30

// RGB Configs
#define LAYER_STATE_8BIT
